---
title: "CARPS Reproducibility Report"
output:
  html_document:
    toc: true
    toc_float: true
---

#### Article ID: [CARPS_4-1-2015_PS]
#### Pilot 1: [Sean Zion]
#### Co-pilot: [Mufan Luo]
#### Start date: [11/5/2017]
#### End date: [11/6/2017]   

-------

#### Methods summary: 
[Write a brief summary of the methods underlying the target outcomes written in your own words]

------

#### Target outcomes: 
[Insert the target outcomes identified in targetOutcomes.md]  

------

[The chunk below sets up some formatting options for the R Markdown document]

```{r global_options, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, warning=FALSE, message=FALSE)
```

## Step 1: Load packages

[Some useful packages are being loaded below. You can add any additional ones you might need too.]

```{r}
library(tidyverse) # for data munging
library(knitr) # for kable table formating
library(haven) # import and export 'SPSS', 'Stata' and 'SAS' Files
library(readxl) # import excel files
library(CARPSreports) # custom report functions
library(ggplot2)
library(psych)
library(plyr)
library(corrplot)
library(car)
```

## Step 2: Load data

```{r}
faces <- read.csv("/Users/seanzion/Documents/GitHub/CARPS_4-1-2015_PS/data/Experiment _1_Rps _v2.csv")
```

## Step 3: Tidy data

```{r}
faces$id <- c(1:48) #adding a new column for subject ID

tidyfaces <- faces %>%
  gather(key="DFT_Rating", value, 3:35) %>%
  separate(DFT_Rating, c("dft", "value_trial"), sep="T_") %>%
  subset(select = -dft) %>%
  separate(value_trial, c("dft_value", "trial_num"), sep="_") %>% 
  spread(trial_num, value)

```

## Step 4: Run analysis

### Pre-processing


```{r}
colnames(tidyfaces) <- c("age", "trust_attract", "id", "dft_value", "trial_1", "trial_2", "trial_3") #renaming the columns 

avg_value <-rowMeans(tidyfaces[,5:7]) #Calculating the avg value for each participant across the three tirals
tidyfaces$avg_value <- avg_value #adding this column into the dataframe

tidyfaces$dft_value <- as.numeric(tidyfaces$dft_value)
tidyfaces$trust_attract <- as.factor(tidyfaces$trust_attract)
```

### Descriptive statistics

```{r}
#Mean and SD for ratings across judement type (trustworthy / attractiveness):

tidyfaces %>%
  filter(trust_attract==1) %>%
  summarise(mean = mean(avg_value), 
            sd = sd(avg_value))

tidyfaces %>%
  filter(trust_attract==0) %>%
  summarise(mean = mean(avg_value), 
            sd = sd(avg_value))

attract_mean = c()
attract_sd = c()
trust_mean = c()
trust_sd = c()

for (i in 0:10){
  a = tidyfaces %>%
  filter(trust_attract==0 & dft_value == 10*i) %>%
  summarise(mean = mean(avg_value), 
            sd = sd(avg_value))
  attract_mean = c(attract_mean, a$mean)
  attract_sd = c(attract_sd, a$sd)

  
  t = tidyfaces %>%
  filter(trust_attract==1 & dft_value == 10*i) %>%
  summarise(mean = mean(avg_value), 
            sd = sd(avg_value))
  trust_mean = c(trust_mean, t$mean)
  trust_sd = c(trust_sd, t$sd)
}

df = data.frame("dft_value"=seq(0,100,10))
df = mutate(df, "trust_mean" = trust_mean
            , "trust_sd" = trust_sd
            , "attract_mean" = attract_mean
            , "attract_sd" = attract_sd)

```

### Inferential statistics

```{r}

#Model 1 - Repeated Measures ANOVA 
tidyfaces$trust_attract = as.factor(tidyfaces$trust_attract)
tidyfaces$dft_value = as.factor(tidyfaces$dft_value)
tidyfaces$id = as.factor(tidyfaces$id)
model1 <- with(tidyfaces, aov(avg_value ~ dft_value * trust_attract + Error(id / dft_value)))
summary(model1)

library(ez)

#Model 2 - Repeated Measures ANOVA
tidyfaces$trust_attract <- as.factor(tidyfaces$trust_attract)
tidyfaces$dft_value <- as.factor(tidyfaces$dft_value)
tidyfaces$id <- as.factor(tidyfaces$id)
model2 <- ezANOVA(data = tidyfaces, dv = .(avg_value), wid = .(id), within = .(dft_value), between = .(trust_attract), detailed = TRUE, return_aov=T)

model2$ANOVA

pd <- position_dodge(0.1)
ggplot() + 
  geom_line(data = df, aes(x = dft_value, y = attract_mean), color = "green") + 
    geom_errorbar(aes(x = df$dft_value, ymin = attract_mean - attract_sd/sqrt(528), ymax = attract_mean + attract_sd/sqrt(528)), width=.1, position = pd)  + geom_line(data = df, aes(x = dft_value, y = trust_mean), color = "blue") +
  geom_errorbar(aes(x = df$dft_value, ymin = trust_mean - trust_sd/sqrt(528), ymax = trust_mean + trust_sd/sqrt(528)), width=.1,
position = pd)  +  xlab('DFT Value') + ylab('Mean Judgment') + ylim(0, 10) + scale_x_continuous(breaks=seq(0,100,10))

```

## Step 5: Conclusion

[Include the carpsReport function below]

```{r}
# You can delete this commented text for your report, it is here to serve as a guide.
# Use the carpsReport() function in this code chunk.
# Here is a guide to the arguments you should include in the function:
# Report_Type: Enter 'pilot' or 'final'
# Article_ID: Enter the article's unique ID code
# Insufficient_Information_Errors: Enter the number of Insufficient Information Errors
# Decision_Errors Enter: the number of decision errors
# Major_Numerical_Errors: Enter the number of major numerical errors
# Time_to_Complete: Enter the estimated time to complete the report in minutes
# Author_Assistance: Enter whether author assistance was required (TRUE/FALSE)
# FOR EXAMPLE:
# carpsReport(Report_Type = "pilot", 
#             Article_ID = "ABhgyo", 
#             Insufficient_Information_Errors = 0, 
#             Decision_Errors = 1, 
#             Major_Numerical_Errors = 4, 
#             Time_to_Complete = 120, 
#             Author_Assistance = TRUE)
```

[Please also include a brief text summary describing your findings. If this reproducibility check was a failure, you should note any suggestions as to what you think the likely cause(s) might be.]

[This function will output information about the package versions used in this report:]

```{r session_info, include=TRUE, echo=TRUE, results='markup'}
devtools::session_info()
```
